# Stage 1: Build Stage
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_GOOGLE_MAPS_API_KEY
ARG VITE_VIETMAP_API_KEY
ARG VITE_VIETMAP_TILEMAP_API_KEY
ARG VITE_API_URL=""

ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
ENV VITE_VIETMAP_API_KEY=$VITE_VIETMAP_API_KEY
ENV VITE_VIETMAP_TILEMAP_API_KEY=$VITE_VIETMAP_TILEMAP_API_KEY
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Stage 2: Production Stage
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
