# Server Config
server.port=8085

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://${DB_HOST:ep-royal-fire-aoiz7fa3-pooler.c-2.ap-southeast-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:neondb}?sslmode=require
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_BOrUQXh3KA1G}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations (Minimum 256-bit key in hex)
adora.jwt.secret=${JWT_SECRET:9a4f2c8d3b7a1e5f8c6d4b2a0f8e6d4c2b0a8f6e4d2c0b8a6f4e2d0c8b6a4f2e}
# 86400000 ms = 24 hours
adora.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Google Integration
adora.google.client-id=${GOOGLE_CLIENT_ID:948345920089-7j515dqe1ihqph3lnapho8c7l6auo9r8.apps.googleusercontent.com}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tienhung1201@gmail.com
spring.mail.password=lfjrcgyzckgznfsl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
