import { BillboardDto } from "../../types/billboard";

export const DANANG_CENTER = { lat: 16.0544, lng: 108.2022 };

export type RentalStatus = "available" | "booked";

const DISTRICT_COORDS: Record<string, { lat: number; lng: number }> = {
  "Hải Châu": { lat: 16.0678, lng: 108.2208 },
  "Sơn Trà": { lat: 16.102, lng: 108.251 },
  "Thanh Khê": { lat: 16.062, lng: 108.189 },
  "Ngũ Hành Sơn": { lat: 16.003, lng: 108.263 },
  "Liên Chiểu": { lat: 16.082, lng: 108.153 },
  "Cẩm Lệ": { lat: 16.018, lng: 108.21 },
  "Hòa Vang": { lat: 15.995, lng: 108.08 },
};

export function getBillboardThumbnail(b: BillboardDto): string {
  return (
    b.images?.find((img) => img.isThumbnail)?.imageUrl ||
    b.images?.[0]?.imageUrl ||
    "https://images.unsplash.com/photo-1585504303098-9785dc784742?w=800"
  );
}

export function getBillboardRentalStatus(b: BillboardDto): RentalStatus {
  if (b.availabilities?.some((av) => av.status === "BOOKED" || av.status === "BLOCKED")) {
    return "booked";
  }
  return "available";
}

export function resolveBillboardPosition(
  b: BillboardDto
): { lat: number; lng: number } {
  return {
    lat: b.latitude || DANANG_CENTER.lat,
    lng: b.longitude || DANANG_CENTER.lng,
  };
}

export function formatBillboardPrice(b: BillboardDto): string {
  return `${b.pricePerDay.toLocaleString("vi-VN")}₫/ngày`;
}

export function formatBillboardSize(b: BillboardDto): string {
  return `${b.width}m × ${b.height}m`;
}

export function getGoogleMapsApiKey(): string {
  const key = import.meta.env.VITE_GOOGLE_MAPS_API_KEY?.trim() ?? "";
  if (
    !key ||
    key === "YOUR_GOOGLE_MAPS_API_KEY" ||
    key === "your_google_maps_api_key_here" ||
    key.includes("YOUR_")
  ) {
    return "";
  }
  return key;
}

const RAW_BILLBOARD_MOCKS = [
  {
    id: 1,
    title: "Cầu Rồng LED",
    description: "Bảng quảng cáo vị trí đắc địa tại Cầu Rồng Đà Nẵng, lưu lượng giao thông cực kỳ đông đúc cả ngày lẫn đêm.",
    address: "Đường 2/9, Hải Châu",
    city: "Đà Nẵng",
    district: "Hải Châu",
    latitude: 16.0614,
    longitude: 108.2275,
    width: 14,
    height: 6,
    resolution: "1920x1080",
    brightness: 6500,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 3000000,
    pricePerMonth: 85000000,
    locationSurcharge: 1.1,
    status: "APPROVED",
    dailyViews: 120000,
    isFeatured: true,
    demoVideoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    images: [{ id: 1, imageUrl: "https://images.unsplash.com/photo-1585504303098-9785dc784742?w=1080", isThumbnail: true }],
    features: [{ id: 1, name: "Độ sáng cao" }],
    availabilities: [],
  },
  {
    id: 2,
    title: "Bạch Đằng Digital",
    description: "Bảng quảng cáo ven sông Bạch Đằng hướng nhìn trực diện sông Hàn, phù hợp các chiến dịch thương hiệu cao cấp.",
    address: "Đường Bạch Đằng, Sơn Trà",
    city: "Đà Nẵng",
    district: "Sơn Trà",
    latitude: 16.0708,
    longitude: 108.2483,
    width: 10,
    height: 4,
    resolution: "1920x1080",
    brightness: 6000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 2000000,
    pricePerMonth: 55000000,
    locationSurcharge: 1.05,
    status: "APPROVED",
    dailyViews: 80000,
    isFeatured: true,
    demoVideoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    images: [{ id: 1, imageUrl: "https://images.unsplash.com/photo-1745725427643-8994370391e6?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 3,
    title: "Nguyễn Văn Linh Screen",
    description: "Nằm ngay ngã ba Nguyễn Văn Linh và Nguyễn Tri Phương, đón đầu luồng giao thông từ sân bay vào trung tâm.",
    address: "Đường Nguyễn Văn Linh, Thanh Khê",
    city: "Đà Nẵng",
    district: "Thanh Khê",
    latitude: 16.0545,
    longitude: 108.202,
    width: 12,
    height: 5,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 2500000,
    pricePerMonth: 68000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 110000,
    isFeatured: true,
    images: [{ id: 1, imageUrl: "https://images.unsplash.com/photo-1765908310161-1005cf85586d?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [{ id: 1, availableDate: "2026-05-23", status: "BOOKED" }],
  },
  {
    id: 4,
    title: "Mỹ Khê Beach LED",
    description: "Màn hình LED ven biển Mỹ Khê, tiếp cận du khách quốc tế và cộng đồng resort cao cấp.",
    address: "Võ Nguyên Giáp, Ngũ Hành Sơn",
    city: "Đà Nẵng",
    district: "Ngũ Hành Sơn",
    latitude: 16.003,
    longitude: 108.263,
    width: 8,
    height: 3,
    resolution: "1920x1080",
    brightness: 5500,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "14h/ngày",
    pricePerDay: 1400000,
    pricePerMonth: 42000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 65000,
    isFeatured: false,
    images: [{ id: 1, imageUrl: "https://images.unsplash.com/photo-1766324488354-a189b706d3e2?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 5,
    title: "Vincom Plaza LED",
    description: "Màn hình LED lớn ốp tường Vincom Plaza Hải Châu, tiếp cận hàng ngàn lượt mua sắm mỗi ngày.",
    address: "Ngô Quyền, Hải Châu",
    city: "Đà Nẵng",
    district: "Hải Châu",
    latitude: 16.0678,
    longitude: 108.2208,
    width: 16,
    height: 8,
    resolution: "1920x1080",
    brightness: 5500,
    refreshRate: 3840,
    screenType: "Building LED",
    operatingHours: "18h/ngày",
    pricePerDay: 4000000,
    pricePerMonth: 120000000,
    locationSurcharge: 1.15,
    status: "APPROVED",
    dailyViews: 150000,
    isFeatured: true,
    demoVideoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    images: [{ id: 1, imageUrl: "https://images.unsplash.com/photo-1676491405940-9cd5d8cbf954?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 6,
    title: "01 Trần Phú, Hải Châu",
    description: "Bảng quảng cáo LED ngoài trời nằm trên đường Trần Phú - một trong những trục đường chính sầm uất nhất trung tâm Hải Châu.",
    address: "01 Trần Phú, Hải Châu",
    city: "Đà Nẵng",
    district: "Hải Châu",
    latitude: 16.0805,
    longitude: 108.2230,
    width: 10,
    height: 4,
    resolution: "1920x1080",
    brightness: 6000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 1750000,
    pricePerMonth: 52000000,
    locationSurcharge: 1.05,
    status: "APPROVED",
    dailyViews: 75000,
    isFeatured: false,
    images: [{ id: 6, imageUrl: "https://images.unsplash.com/photo-1768812785179-ab5add1e2e1c?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 7,
    title: "Hàn River Digital",
    description: "Bảng quảng cáo Led kỹ thuật số cao cấp ngay khu vực Cầu Sông Hàn, thu hút trọn vẹn luồng giao thông qua lại giữa quận Hải Châu và Sơn Trà.",
    address: "Đường Bạch Đằng, Hải Châu",
    city: "Đà Nẵng",
    district: "Hải Châu",
    latitude: 16.0720,
    longitude: 108.2268,
    width: 12,
    height: 6,
    resolution: "1920x1080",
    brightness: 6500,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 2600000,
    pricePerMonth: 78000000,
    locationSurcharge: 1.1,
    status: "APPROVED",
    dailyViews: 120000,
    isFeatured: false,
    images: [{ id: 7, imageUrl: "https://images.unsplash.com/photo-1770259406469-b83c307b2dca?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 8,
    title: "Liên Chiểu Gateway",
    description: "Bảng quảng cáo đón đầu tại cửa ngõ phía Bắc thành phố, trục đường chính Tôn Đức Thắng tiếp cận lượng lớn xe khách và sinh viên các trường đại học.",
    address: "Đường Tôn Đức Thắng, Hòa Minh, Liên Chiểu",
    city: "Đà Nẵng",
    district: "Liên Chiểu",
    latitude: 16.0690,
    longitude: 108.1620,
    width: 8,
    height: 4,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 1300000,
    pricePerMonth: 38000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 50000,
    isFeatured: false,
    images: [{ id: 8, imageUrl: "https://images.unsplash.com/photo-1585504303098-9785dc784742?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 9,
    title: "Cẩm Lệ Center LED",
    description: "Tọa lạc tại trung tâm quận Cẩm Lệ, tiếp cận luồng giao thông chính qua các nút giao lớn kết nối các khu đô thị mới.",
    address: "Đường Ông Ích Đường, Khuê Trung, Cẩm Lệ",
    city: "Đà Nẵng",
    district: "Cẩm Lệ",
    latitude: 16.0210,
    longitude: 108.2030,
    width: 10,
    height: 5,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 1500000,
    pricePerMonth: 45000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 60000,
    isFeatured: false,
    images: [{ id: 9, imageUrl: "https://images.unsplash.com/photo-1745725427643-8994370391e6?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 11,
    title: "Vòng xoay Phạm Văn Đồng LED",
    description: "Màn hình LED lớn tại vòng xoay Phạm Văn Đồng - Ngô Quyền, đón đầu lượng giao thông từ cầu Sông Hàn ra bãi biển Mỹ Khê.",
    address: "Vòng xoay Phạm Văn Đồng - Ngô Quyền, An Hải Bắc, Sơn Trà",
    city: "Đà Nẵng",
    district: "Sơn Trà",
    latitude: 16.0740,
    longitude: 108.2445,
    width: 12,
    height: 6,
    resolution: "1920x1080",
    brightness: 6000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 3200000,
    pricePerMonth: 95000000,
    locationSurcharge: 1.1,
    status: "APPROVED",
    dailyViews: 110000,
    isFeatured: false,
    images: [{ id: 11, imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 12,
    title: "Võ Văn Kiệt Pedestrian LED",
    description: "Bảng Led quảng cáo tầm thấp tại dải phân cách đường Võ Văn Kiệt, tiếp cận người đi bộ và lưu lượng xe đi ra biển Mỹ Khê.",
    address: "Đường Võ Văn Kiệt, Phước Mỹ, Sơn Trà",
    city: "Đà Nẵng",
    district: "Sơn Trà",
    latitude: 16.0645,
    longitude: 108.2415,
    width: 8,
    height: 4,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Street LED",
    operatingHours: "16h/ngày",
    pricePerDay: 1400000,
    pricePerMonth: 42000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 45000,
    isFeatured: false,
    images: [{ id: 12, imageUrl: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 13,
    title: "Ngã Tư Điện Biên Phủ LED",
    description: "Bảng quảng cáo LED ngoài trời tại nút giao thông ngã tư Điện Biên Phủ - Nguyễn Tri Phương, nơi có mật độ giao thông cực kỳ cao.",
    address: "Ngã tư Điện Biên Phủ - Nguyễn Tri Phương, Chính Gián, Thanh Khê",
    city: "Đà Nẵng",
    district: "Thanh Khê",
    latitude: 16.0655,
    longitude: 108.1970,
    width: 14,
    height: 7,
    resolution: "1920x1080",
    brightness: 6500,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 3000000,
    pricePerMonth: 88000000,
    locationSurcharge: 1.05,
    status: "APPROVED",
    dailyViews: 115000,
    isFeatured: false,
    images: [{ id: 13, imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 14,
    title: "Nguyễn Tất Thành Street Screen",
    description: "Màn hình LED dọc tuyến đường ven biển Nguyễn Tất Thành, phù hợp cho các chiến dịch quảng bá địa phương.",
    address: "Đường Nguyễn Tất Thành, Xuân Hà, Thanh Khê",
    city: "Đà Nẵng",
    district: "Thanh Khê",
    latitude: 16.0758,
    longitude: 108.1835,
    width: 8,
    height: 4,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Street LED",
    operatingHours: "16h/ngày",
    pricePerDay: 1300000,
    pricePerMonth: 38000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 35000,
    isFeatured: false,
    images: [{ id: 14, imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 15,
    title: "Võ Nguyên Giáp Beachfront LED",
    description: "Vị trí đắc địa mặt tiền biển Võ Nguyên Giáp, tiếp cận lượng lớn khách du lịch trong nước và quốc tế.",
    address: "Đường Võ Nguyên Giáp, Khuê Mỹ, Ngũ Hành Sơn",
    city: "Đà Nẵng",
    district: "Ngũ Hành Sơn",
    latitude: 16.0544,
    longitude: 108.2477,
    width: 12,
    height: 6,
    resolution: "1920x1080",
    brightness: 6000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 3100000,
    pricePerMonth: 90000000,
    locationSurcharge: 1.1,
    status: "APPROVED",
    dailyViews: 95000,
    isFeatured: false,
    images: [{ id: 15, imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 16,
    title: "Lê Văn Hiến Street Screen",
    description: "Màn hình LED kỹ thuật số nằm trên trục đường chính Lê Văn Hiến kết nối Đà Nẵng và Hội An.",
    address: "Đường Lê Văn Hiến, Hòa Hải, Ngũ Hành Sơn",
    city: "Đà Nẵng",
    district: "Ngũ Hành Sơn",
    latitude: 15.9920,
    longitude: 108.2610,
    width: 8,
    height: 4,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Street LED",
    operatingHours: "14h/ngày",
    pricePerDay: 1200000,
    pricePerMonth: 35000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 30000,
    isFeatured: false,
    images: [{ id: 16, imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 17,
    title: "Tôn Đức Thắng Junction LED",
    description: "Nằm ngay trục đường giao thông huyết mạch Tôn Đức Thắng, gần bến xe trung tâm thành phố Đà Nẵng.",
    address: "Đường Tôn Đức Thắng, Hòa Minh, Liên Chiểu",
    city: "Đà Nẵng",
    district: "Liên Chiểu",
    latitude: 16.0615,
    longitude: 108.1685,
    width: 10,
    height: 5,
    resolution: "1920x1080",
    brightness: 6000,
    refreshRate: 3840,
    screenType: "Outdoor LED",
    operatingHours: "16h/ngày",
    pricePerDay: 2200000,
    pricePerMonth: 65000000,
    locationSurcharge: 1.05,
    status: "APPROVED",
    dailyViews: 75000,
    isFeatured: false,
    images: [{ id: 17, imageUrl: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 18,
    title: "Nguyễn Lương Bằng Campus Screen",
    description: "Màn hình quảng cáo trước khu đô thị công nghệ cao Nguyễn Lương Bằng, gần các trường đại học lớn.",
    address: "Đường Nguyễn Lương Bằng, Hòa Khánh Bắc, Liên Chiểu",
    city: "Đà Nẵng",
    district: "Liên Chiểu",
    latitude: 16.0750,
    longitude: 108.1520,
    width: 8,
    height: 4,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Street LED",
    operatingHours: "16h/ngày",
    pricePerDay: 950000,
    pricePerMonth: 28000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 25000,
    isFeatured: false,
    images: [{ id: 18, imageUrl: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 19,
    title: "Nguyễn Hữu Thọ Avenue LED",
    description: "Màn hình LED lớn ốp tường tại đại lộ Nguyễn Hữu Thọ, tiếp cận luồng giao thông từ các quận phía Nam vào trung tâm.",
    address: "Đường Nguyễn Hữu Thọ, Khuê Trung, Cẩm Lệ",
    city: "Đà Nẵng",
    district: "Cẩm Lệ",
    latitude: 16.0270,
    longitude: 108.2095,
    width: 10,
    height: 5,
    resolution: "1920x1080",
    brightness: 5500,
    refreshRate: 3840,
    screenType: "Building LED",
    operatingHours: "18h/ngày",
    pricePerDay: 2000000,
    pricePerMonth: 60000000,
    locationSurcharge: 1.05,
    status: "APPROVED",
    dailyViews: 70000,
    isFeatured: false,
    images: [{ id: 19, imageUrl: "https://images.unsplash.com/photo-1472214222555-d404758b1c42?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
  {
    id: 20,
    title: "Cách Mạng Tháng Tám Highway Screen",
    description: "Bảng quảng cáo LED tầm trung trên quốc lộ Cách Mạng Tháng Tám hướng đi cầu vượt Hòa Cầm.",
    address: "Đường Cách Mạng Tháng Tám, Hòa Thọ Đông, Cẩm Lệ",
    city: "Đà Nẵng",
    district: "Cẩm Lệ",
    latitude: 16.0290,
    longitude: 108.2160,
    width: 10,
    height: 5,
    resolution: "1280x720",
    brightness: 5000,
    refreshRate: 3840,
    screenType: "Street LED",
    operatingHours: "16h/ngày",
    pricePerDay: 1000000,
    pricePerMonth: 30000000,
    locationSurcharge: 1,
    status: "APPROVED",
    dailyViews: 40000,
    isFeatured: false,
    images: [{ id: 20, imageUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1080", isThumbnail: true }],
    features: [],
    availabilities: [],
  },
];

export const MAP_BILLBOARD_MOCKS: BillboardDto[] = RAW_BILLBOARD_MOCKS.map((b) => ({
  ...b,
  formattedAddress: (b as any).formattedAddress || `${b.address}, ${b.city}`,
  addressDetail: (b as any).addressDetail || "",
  ward: (b as any).ward || "",
})) as BillboardDto[];
